esphome:
  name: heltec-433
  friendly_name: Heltec 433

esp32:
  board: heltec_wifi_lora_32_V3
  variant: esp32s3
  framework:
    type: arduino
    version: 2.0.14
    platform_version: 6.5.0

external_components:
  source: github://smartoctopus/RadioLib-esphome

logger:

api:
  encryption:
    key: !secret key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

button:
  # Restart the ESP
  - platform: restart
    name: "Restart"

