substitutions:
  name: ble
  friendly_name: Bluetooth LE

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: nick.bluetooth-proxy
    version: "1.1"
  platformio_options:
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
    board_build.flash_size: 4MB
  # on_boot:
  #   priority: 250
  #   then:
  #     - delay: 15s
  #     - lambda: |-
  #         id(ble_tracker).set_scan_continuous(true); 
  #         id(ble_tracker).start_scan();

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: n    

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .home
  fast_connect: true

api:
  encryption:
    key: !secret key

logger:
  baud_rate: 115200
  hardware_uart: UART0
  level: VERY_VERBOSE
  logs:
    sensor: DEBUG
    esp32: DEBUG
    esp32_ble: DEBUG

ota:
  on_begin:
    then:
      - logger.log: "OTA start"

  on_end:
    then:
      - logger.log: "OTA end"

  on_error:
    then:
      - logger.log:
          format: "OTA update error %d"
          args: ["x"]


time:
  - platform: sntp
    id: sntp_time

sensor:
  # WiFi Signal Sensor
  - platform: wifi_signal
    name: "${friendly_name} WiFi Status"
    update_interval: 60s

# dashboard_import:
#   package_import_url: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main

esp32_ble_tracker:
  # id: ble_tracker
  # scan_parameters:
    # active: true
    # continuous: false
    # interval: 211ms
    # window: 120ms

# bluetooth_proxy:
#   active: true

button:
  - platform: safe_mode
    name: ${friendly_name} Safe Mode Boot
    entity_category: diagnostic

  - platform: restart
    name: ${friendly_name} Restart
