substitutions:
  devicename: hayley-study
  fullname: Hayley study

esphome:
  name: $devicename
  platform: ESP32
  board: wemos_d1_mini32

wifi:
  ssid: "oakridge"
  password: "donkeykong"
  domain: .home

captive_portal:

# Enable logging
logger:
  level: info

ota:
  password: !secret ota_password

api:
  encryption:
    key: !secret key

time:
  - platform: sntp

switch:
  - platform: restart
    name: ${fullname} Restart

i2c:
  sda: 21
  scl: 22
  scan: True
  id: bus_a

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

bme680_bsec:
  address: 0x77

  # Temperature offset
  # ------------------
  # Useful if device is in enclosure and reads too high
  # Default: 0
  temperature_offset: 0

  # IAQ calculation mode
  # --------------------
  # Available options:
  # - static (for fixed position devices)
  # - mobile (for on person or other moveable devices)
  # Default: static
  iaq_mode: static

  # Sample rate
  # -----------
  # Available options:
  # - lp (low power - samples every 3 seconds)
  # - ulp (ultra low power - samples every 5 minutes)
  # Default: lp
  sample_rate: lp

  # Interval at which to save BSEC state
  # ------------------------------------
  # Default: 6h
  state_save_interval: 6h

sensor:
  - platform: bh1750
    name: ${fullname} Illuminance
    address: 0x23
    update_interval: 60s

  - platform: bme680_bsec
    temperature:
      # Temperature in °C
      name: ${fullname} Temperature
      filters:
        - median
    pressure:
      # Pressure in hPa
      name: ${fullname} Pressure
      filters:
        - median
    humidity:
      # Relative humidity %
      name: ${fullname} Humidity
      filters:
        - median
    gas_resistance:
      # Gas resistance in Ω
      name: ${fullname} Gas Resistance
      filters:
        - median
    iaq:
      # Indoor air quality value
      name: ${fullname} IAQ
      filters:
        - median
    iaq_accuracy:
      # IAQ accuracy as a numeric value of 0, 1, 2, 3
      name: ${fullname} Numeric IAQ Accuracy
    co2_equivalent:
      # CO2 equivalent estimate in ppm
      name: ${fullname} CO2 Equivalent
      filters:
        - median
    breath_voc_equivalent:
      # Volatile organic compounds equivalent estimate in ppm
      name: ${fullname} Breath VOC Equivalent
      filters:
        - median

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      # IAQ accuracy as a text value of Stabilizing, Uncertain, Calibrating, Calibrated
      name: ${fullname} IAQ Accuracy
