esphome:
  name: rf-bridge
  friendly_name: rf-bridge

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret key

  # services:
  #   - service: send_rf_code
  #     variables:
  #       sync: int
  #       low: int
  #       high: int
  #       code: int
  #     then:
  #       - rf_bridge.send_code:
  #           sync: !lambda 'return sync;'
  #           low: !lambda 'return low;'
  #           high: !lambda 'return high;'
  #           code: !lambda 'return code;'
  #   - service: learn
  #     then:
  #       - rf_bridge.learn

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain


button:
  # Restart the ESP
  - platform: restart
    name: "Restart"

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 19200



# Sensors for ESP version and WIFI information
text_sensor:
  # ESPHome version
  - platform: version
    hide_timestamp: true
    name: "ESPHome Version"
  # IP address and connected SSID
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: mdi:wifi
    ssid:
      name: "Connected SSID"
      icon: mdi:wifi-strength-2
sensor:
  # WiFi signal
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 120s
  - platform: uptime
    name: Sonoff RF Bridge Uptime


light:
  - platform: status_led
    name: "Switch state"
    pin: GPIO13    

remote_receiver:
  tolerance: 50%
  filter: 250us
  idle: 4ms
  buffer_size: 2kb  
  pin: GPIO4
  dump: raw

remote_transmitter:
  pin: GPIO5
  carrier_duty_percent: 100%  

# switch:
#   - platform: template
#     name: Blinds up
#     turn_on_action:
#       remote_transmitter.transmit_raw:
#         code: '1011010100010001000001001100000100010001'
#         protocol: 6
#         repeat:
#           times: 3
#   - platform: template
#     name: Blinds down
#     turn_on_action:
#       remote_transmitter.transmit_raw:
#         code: [264,1922]

#   - platform: template
#     name: Blinds pause
#     turn_on_action:
#       remote_transmitter.transmit_raw:
#         code: [230,1918]

binary_sensor:
  - platform: status
    name: Sonoff RF Bridge Status  

  # - platform: remote_receiver
  #   name: "Blinds up"
  #   pronto:
  #     data: 0000 006D 0001 0000 0009 0181 06C3

  # - platform: remote_receiver
  #   name: "Blinds pause"
  #   pronto:
  #     data: 0000 006D 0001 0000 000A 0181 06C3

  # - platform: remote_receiver
  #   name: "Blinds down"
  #   pronto:
  #     data: 0000 006D 0001 0000 0008 0181 06C3
